ALTER TABLE T_VEHICLE_POSITION_TRANSACTION
    ADD COLUMN attributed_player_id BIGINT;
ALTER TABLE T_VEHICLE_POSITION_TRANSACTION
    ADD COLUMN attribution_method VARCHAR(80);
ALTER TABLE T_VEHICLE_POSITION_TRANSACTION
    ADD COLUMN movement_valid BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE T_VEHICLE_POSITION_TRANSACTION
    ADD CONSTRAINT fk_t_vehicle_position_attributed_player
        FOREIGN KEY (attributed_player_id) REFERENCES M_PLAYER(id);

ALTER TABLE T_PLAYER_POSITION_TRANSACTION
    ADD COLUMN movement_mode VARCHAR(20) NOT NULL DEFAULT 'UNKNOWN';
ALTER TABLE T_PLAYER_POSITION_TRANSACTION
    ADD COLUMN vehicle_entity_id INTEGER;
ALTER TABLE T_PLAYER_POSITION_TRANSACTION
    ADD COLUMN movement_inference_method VARCHAR(80);

CREATE INDEX idx_t_vehicle_position_driver_occurred_at
    ON T_VEHICLE_POSITION_TRANSACTION (attributed_player_id, occurred_at);

CREATE INDEX idx_t_player_position_mode_occurred_at
    ON T_PLAYER_POSITION_TRANSACTION (movement_mode, occurred_at);
