ALTER TABLE T_SLEEPER_TRANSACTION
    ADD COLUMN player_position_x INTEGER;

ALTER TABLE T_SLEEPER_TRANSACTION
    ADD COLUMN player_position_y INTEGER;

ALTER TABLE T_SLEEPER_TRANSACTION
    ADD COLUMN player_position_z INTEGER;

ALTER TABLE T_SLEEPER_TRANSACTION
    ADD COLUMN player_current_state_updated_at TIMESTAMP WITH TIME ZONE;
